# Generated by Django 2.1.5 on 2020-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='amount',
            name='interest',
            field=models.IntegerField(),
        ),
    ]
